version: '3.4'

services:
  managemantsclient:
    image: ${DOCKER_REGISTRY-}managemantsclient
    build:
      context: .
      dockerfile: ManagemAntsClient/Dockerfile
    ports:
        - "8082:80"
    depends_on:
        - managemantsserver
        
  managemantsserver:
    image: ${DOCKER_REGISTRY-}managemantsserver
    build:
      context: .
      dockerfile: ManagemAntsServer/Dockerfile